require 'rake/extensiontask'
require 'rake/testtask'

spec = Gem::Specification.load('sereal.gemspec')
Rake::ExtensionTask.new('sereal', spec)
Rake::TestTask.new do |t|
  t.libs << 'test'
end
desc "Run tests"
task :default => :compile
