SRL_MAGIC_STRING_HIGHBIT            = "=\xF3rl"
SRL_MAGIC_STRING_HIGHBIT_UINT_LE    = '0x6c72f33d'

SRL_TRACK_BIT                       = 128
SRL_SHORT_BINARY_LEN                = 31

SRL_TYPE_POS_0                      = 0
SRL_NEG_16                          = 16
SRL_TYPE_VARINT                     = 32
SRL_TYPE_ZIGZAG                     = 33
SRL_TYPE_FLOAT                      = 34
SRL_TYPE_DOUBLE                     = 35
SRL_TYPE_UNDEF                      = 37
SRL_TYPE_BINARY                     = 38
SRL_TYPE_STR_UTF8                   = 39
SRL_TYPE_REFN                       = 40
SRL_TYPE_REFP                       = 41
SRL_TYPE_HASH                       = 42
SRL_TYPE_ARRAY                      = 43
SRL_TYPE_OBJECT                     = 44
SRL_TYPE_OBJECTV                    = 45
SRL_TYPE_COPY                       = 47
SRL_TYPE_REGEXP                     = 49
SRL_TYPE_CANONICAL_UNDEF            = 57
SRL_TYPE_FALSE                      = 58
SRL_TYPE_TRUE                       = 59
SRL_TYPE_ARRAYREF_0                 = 64
SRL_TYPE_HASHREF_0                  = 80
SRL_TYPE_SHORT_BINARY_0             = 96
