void s_init_writers(void);
static void rb_object_to_sereal(sereal_t *s, VALUE object);
static void s_append_varint(sereal_t *s,u64 n);
static void s_append_hdr_with_varint(sereal_t *s,u8 hdr, u64 n);
static void s_append_zigzag(sereal_t *s,u64 n);
static void s_append_string(sereal_t *s,u8 *string, u32 len,u8 is_utf8);
static void s_append_rb_string(sereal_t *s, VALUE object);
static void s_append_array(sereal_t *s, VALUE object);
static void s_append_hash(sereal_t *s, VALUE object);
static void s_append_symbol(sereal_t *s, VALUE object);
static void s_append_object(sereal_t *s, VALUE object);
static void s_append_regexp(sereal_t *s, VALUE object);
static void s_append_integer(sereal_t *s, VALUE object);
static void s_append_double(sereal_t *s, VALUE object);
static void s_append_true(sereal_t *s, VALUE object);
static void s_append_false(sereal_t *s, VALUE object);
static void s_append_nil(sereal_t *s, VALUE object);
static void s_default_writer(sereal_t *s, VALUE object);
extern void (*WRITER[sizeof(T_FIXNUM)])(sereal_t *,VALUE);
