#!/bin/bash
pushd ~/git_tree/Sereal/Perl/Encoder
perl Makefile.PL
make
popd
pushd ~/git_tree/Sereal/Perl/Decoder
perl Makefile.PL
make
popd
if [ "$#" != "0" ]
then
    pushd ~/git_tree/Sereal/Perl/Encoder
    make "$@"
    popd
    pushd ~/git_tree/Sereal/Perl/Decoder
    make "$@"
    popd
fi


